apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
  namespace: $NAMESPACE
spec:
  replicas: 8
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: $DOCKER_TAG
      creationTimestamp: null
      labels:
        app: $PROJECT_NAME
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: $CONFIG_MAP
        - secretRef:
            name: $SECRET_REF
        image: $DOCKER_TAG
        volumeMounts:
        - mountPath: /var/www/html/public/uploades
          name: nfs-volume-basys
        imagePullPolicy: IfNotPresent
        name: $PROJECT_NAME       
        ports:
        - containerPort: 80
          name: msg-port
          protocol: TCP
        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: 1Gi
        #   requests:
        #     cpu: 500m
        #     memory: 500Mi
      imagePullSecrets:
      - name: registry-hacathon.oss.net.bd
      volumes:
      - name: nfs-volume-basys
        nfs:
          path: /var/k8s-nfs/ba-sys
          server: 192.168.60.15      
      restartPolicy: Always
