
apiVersion: v1
data: 
  APP_DEBUG: "false"
  APP_ENV: dev
  APP_KEY: base64:S+FceqtRK3zCswxtv1PLRHw2POAOa7M3fex3W60ViKM=
  APP_NAME: "auth_microservice"
  APP_URL: "https://prod-admin.ba-systems.com"
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ""
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  LOG_CHANNEL: stderr
  MAIN_PORTAL: "https://www.ba-systems.com/"
  MAIL_DRIVER: smtp
  MAIL_ENCRYPTION: ""
  MAIL_FROM_ADDRESS: ""
  MAIL_FROM_NAME: "${APP_NAME}"
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PASSWORD: ""
  MAIL_PORT: "2525"
  MAIL_USERNAME: ""
 

  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  QUEUE_CONNECTION: sync

  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"

kind: ConfigMap
metadata: 
  name: $CONFIGMAP_NAME
  namespace: $NAMESPACE
